# Generated by Django 3.2.9 on 2021-11-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Contents',
            new_name='contents',
        ),
    ]
